/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MenuController;

/**
 *
 * @author Samuel
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    private final MenuController controller;
    
    public Menu() {
        initComponents();
        
        controller = new MenuController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuMaintenance = new javax.swing.JMenu();
        jMenuItemRegister = new javax.swing.JMenuItem();
        jMenuItemUpdater = new javax.swing.JMenuItem();
        jMenuConsult = new javax.swing.JMenu();
        jMenuItemListing = new javax.swing.JMenuItem();
        jMenuReport = new javax.swing.JMenu();
        jMenuItemReportOfActivePersons = new javax.swing.JMenuItem();
        jMenuItemGeneralReport = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();
        jMenuItemHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/etemb.png"))); // NOI18N

        jMenuMaintenance.setText("Manutenção");

        jMenuItemRegister.setText("Cadastro");
        jMenuItemRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegisterActionPerformed(evt);
            }
        });
        jMenuMaintenance.add(jMenuItemRegister);

        jMenuItemUpdater.setText("Alteração // Exclusão");
        jMenuItemUpdater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUpdaterActionPerformed(evt);
            }
        });
        jMenuMaintenance.add(jMenuItemUpdater);

        jMenuBar.add(jMenuMaintenance);

        jMenuConsult.setText("Consulta");

        jMenuItemListing.setText("Listagem");
        jMenuConsult.add(jMenuItemListing);

        jMenuBar.add(jMenuConsult);

        jMenuReport.setText("Relatórios");

        jMenuItemReportOfActivePersons.setText("Relatório de Pessoas Ativas");
        jMenuReport.add(jMenuItemReportOfActivePersons);

        jMenuItemGeneralReport.setText("Relatório Geral");
        jMenuItemGeneralReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGeneralReportActionPerformed(evt);
            }
        });
        jMenuReport.add(jMenuItemGeneralReport);

        jMenuBar.add(jMenuReport);

        jMenuAbout.setText("Sobre");

        jMenuItemAbout.setText("Sobre");
        jMenuAbout.add(jMenuItemAbout);

        jMenuItemHelp.setText("Ajuda");
        jMenuAbout.add(jMenuItemHelp);

        jMenuBar.add(jMenuAbout);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegisterActionPerformed
        controller.openRegisterView();
    }//GEN-LAST:event_jMenuItemRegisterActionPerformed

    private void jMenuItemUpdaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUpdaterActionPerformed
        controller.openUpdateView();
    }//GEN-LAST:event_jMenuItemUpdaterActionPerformed

    private void jMenuItemGeneralReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGeneralReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemGeneralReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuConsult;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemGeneralReport;
    private javax.swing.JMenuItem jMenuItemHelp;
    private javax.swing.JMenuItem jMenuItemListing;
    private javax.swing.JMenuItem jMenuItemRegister;
    private javax.swing.JMenuItem jMenuItemReportOfActivePersons;
    private javax.swing.JMenuItem jMenuItemUpdater;
    private javax.swing.JMenu jMenuMaintenance;
    private javax.swing.JMenu jMenuReport;
    // End of variables declaration//GEN-END:variables
}
